kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "api-gateway"
spec:
  source:
    git:
      ref: feature1
      uri: 'https://github.com/iftachsc/petclinic-api-gateway.git'
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: microservicesPipline
    type: JenkinsPipeline
  triggers:
    - github:
        secret: secret101
      type: GitHub
